### PR TITLE
Add senaite configs for HSC distro

### PR DESCRIPTION
**Pull request by reagan-meant**

### CODE REVIEW

**Review by Ruhanga — CHANGES_REQUESTED** [review]
Thanks for the PR @reagan-meant. There are a few changes to bring in;
1.) Introduce separate **AR Templates** for all individual tests in the **AR Templates** sheet, these don't have to be tagged to the corresponding Profiles in the `Analysis profile` column.
2.) Attach the introduced **AR Templates** to their `Analysis Service`s in the **AR Template Analyses** sheet.

**Review by Ruhanga — COMMENTED** [review]
@reagan-meant, let's also ensure that the `keyword` for each service on the _Analysis Services_ is short enough, maybe an abbreviation of the full name, without any braces and accented words.
The same applies to the `Profile key` on _Analysis Profiles_ .

**Review by Ruhanga — COMMENTED** [review]
Hi @reagan-meant, you will want to makes more changes in the hsc specific repository instead located here: https://github.com/CRUDEM/senaite-config-hsc

**Comment by rbuisson** [comment]
This file is moved to https://github.com/CRUDEM/senaite-config-hsc/blob/main/configuration/configuration.xlsx

**Pull request closed without merging**
